name: save_the_ocean
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flame: ^1.14.0
  flame_forge2d: ^0.16.0+4
  flame_rive: ^1.9.10
  flame_splash_screen: ^0.2.0
  flutter:
    sdk: flutter
  flutter_responsive_framework: ^0.0.2
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  intl: ^0.19.0
  logging: ^1.2.0
  provider: ^6.1.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: ProtestRevolution
      fonts:
        - asset: assets/fonts/ProtestRevolution-Regular.ttf
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
