name: save_the_ocean
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  flame: ^1.14.0
  flame_forge2d: ^0.16.0+4
  flame_rive: ^1.9.10
  flame_splash_screen: ^0.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  logging: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
