name: save_the_ocean
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  devtools_extensions: ^0.0.9
  firebase_core: ^2.24.2
  flame: ^1.14.0
  flame_audio: ^2.1.8
  flame_forge2d: ^0.17.0
  flame_rive: ^1.9.10
  flame_splash_screen: ^0.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_responsive_framework: ^0.0.2
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  intl: ^0.19.0
  logging: ^1.2.0
  provider: ^6.1.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - assets/audio/sfx/
  fonts:
    - family: ProtestRevolution
      fonts:
        - asset: assets/fonts/ProtestRevolution-Regular.ttf
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
