// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyA6Rb1-nCjlY5dnEgnynURmRDKcMizqE',
    appId: '1:93565432753:web:0711df4f7597fda9b24390',
    messagingSenderId: '93565432753',
    projectId: 'save-the-ocean-4672e',
    authDomain: 'save-the-ocean-4672e.firebaseapp.com',
    storageBucket: 'save-the-ocean-4672e.appspot.com',
    measurementId: 'G-GWZ89PXH2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOAW5OB1lBOZUCZ3_kjCPJnuhrvywX94',
    appId: '1:93565432753:android:1100767621607033b24390',
    messagingSenderId: '93565432753',
    projectId: 'save-the-ocean-4672e',
    storageBucket: 'save-the-ocean-4672e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoI0TcPLtKxPvICxmIpyeyFS_aT_dE2EA',
    appId: '1:93565432753:ios:914250a33d8e306cb24390',
    messagingSenderId: '93565432753',
    projectId: 'save-the-ocean-4672e',
    storageBucket: 'save-the-ocean-4672e.appspot.com',
    iosBundleId: 'com.example.saveTheOcean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoI0TcPLtKxPvICxmIpyeyFS_aT_dE2EA',
    appId: '1:93565432753:ios:2427a2311c7b7f38b24390',
    messagingSenderId: '93565432753',
    projectId: 'save-the-ocean-4672e',
    storageBucket: 'save-the-ocean-4672e.appspot.com',
    iosBundleId: 'com.example.saveTheOcean.RunnerTests',
  );
}
